#$ -cwd
#$ -V
#$ -l h_vmem=4G
#$ -l h_rt=10:00:00
#$ -q iggi-cluster
#$ -t 1-5000
#$ -tc 150
#$ -N hanabi_run
#$ -m e
#$ -M jwr518@york.ac.uk
#$ -o ./results/
#$ -e ./results/

export MALLOC_ARENA_MAX=4
export FIREWORKS_RUN_COUNT=1
vmArgs="-Xmx1024m -XX:ParallelGCThreads=1"
filename=$(awk NR==$SGE_TASK_ID args.txt)
java $vmArgs -cp fireworks-0.1-SNAPSHOT-jar-with-dependencies.jar com.fossgalaxy.games.fireworks.cluster.ValidationGameSingle $filename
